# Include extends
include:
  - project: 'DevOps/gitlab-templates'
    ref: master
    file: '/extends/common.yml'
  - project: 'DevOps/gitlab-templates'
    ref: master
    file: '/extends/wings.yml'

stages:
  - test
  - build
  - update
  - deploy
  - notify

Test:
  image: circleci/node:10-browsers
  stage: test
  script:
    - npm install
    - npm run test:ci
    - npm run test:ci:ui-kit

Build:
  extends: .only-repo
  stage: build
  script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PWD} ${REGISTRY_URL}

    - docker build
        -f ./.build/Dockerfile
        -t ${CONTAINER_FULLNAME}:${CONTAINER_TAG} .
    - docker push ${CONTAINER_FULLNAME}:${CONTAINER_TAG}
  dependencies:
    - Test

update-ssh:
  extends: .update-k8s-testing

Deploy prod:
  variables:
    NAMESPACE: mainnet
    K8S_DEPLOY_CONFIGNAME_LIST: 41_ui-kit.yaml
    SITE_DOMAIN: design.wings.ai
    REPLICAS: 2
  extends: .deploy-mainnet
  environment:
    name: prod_ui-kit
  script:
    - k8s-deploy.sh
    - wait_deployed.sh "${CONTAINER_NAME}" "${WAIT_DEPLOYMENTS}"
  dependencies:
    - Build

# Deploy test:
#   variables:
#     NAMESPACE: default
#     K8S_DEPLOY_CONFIGNAME_LIST: 41_ui-kit.yaml
#     SITE_DOMAIN: ui.wings.toys
#     SITE_SSL: wingstoys-tls-secret
#     REPLICAS: 1
#   extends: .only-repo
#   stage: deploy
#   when: manual
#   before_script:
#     - echo "${K8S_DEPLOY_KUBECONFIG}" | base64 -d > ${KUBECONFIG}
#   environment:
#     name: test_ui-kit
#   script:
#     - k8s-deploy.sh delete
#     - sleep 7
#     - k8s-deploy.sh apply
#     - wait_deployed.sh "${CONTAINER_NAME}" "${WAIT_DEPLOYMENTS}"
#   dependencies:
#     - Build

telegram-notify:
  extends: .telegram-notify
